#defensive moves in a situation where defense is important

# a 'worst case' defensive scenario when attacking 
{'pos_0': [{0: ['east_defense', 8],
            1: ['east_defense', 7],
            2: ['east_defense', 4],
            3: ['east_defense', 8],
            4: ['east_defense', 1]}],
 'pos_4': [{0: ['north_defense', 3],
            1: ['north_defense', 1],
            2: ['north_defense', 9],
            3: ['north_defense', 7],
            4: ['north_defense', 6]},
           {0: ['east_defense', 8],
            1: ['east_defense', 7],
            2: ['east_defense', 4],
            3: ['east_defense', 8],
            4: ['east_defense', 1]},
           {0: ['south_defense', 5],
            1: ['south_defense', 7],
            2: ['south_defense', 4],
            3: ['south_defense', 6],
            4: ['south_defense', 6]}],
 'pos_6': [{0: ['east_defense', 8],
            1: ['east_defense', 7],
            2: ['east_defense', 4],
            3: ['east_defense', 8],
            4: ['east_defense', 1]}]}