# Generated by Django 3.2 on 2021-04-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripleTriadUpdated',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_href', models.TextField(blank=True, null=True)),
                ('card_name', models.TextField(blank=True, null=True)),
                ('image_href', models.TextField(blank=True, null=True)),
                ('north_pole', models.IntegerField(blank=True, null=True)),
                ('west_pole', models.IntegerField(blank=True, null=True)),
                ('east_pole', models.IntegerField(blank=True, null=True)),
                ('south_pole', models.IntegerField(blank=True, null=True)),
                ('card_type', models.IntegerField(blank=True, null=True)),
                ('element_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'triple_triad_updated',
                'managed': False,
            },
        ),
    ]
